/**
 * Renders the static icons the site serves from its root: apple-touch-icon.png
 * (180px, for iOS home screens) and favicon.ico (16, 32 and 48px, for anything
 * that asks for /favicon.ico instead of reading the page's SVG icon).
 *
 * Both come from the same SVG as the in-page favicon, in the default palette,
 * and are written to src/output/icons.ts as base64 so the build and the Docker
 * image need no image tooling. Rerun after changing the icon or the default
 * palette:
 *
 *   npm run build && node scripts/make-icons.mjs && npm run build
 */
import { chromium } from "@playwright/test";
import fs from "node:fs";
import { DEFAULT_PALETTE, faviconSvg } from "../dist/output/theme.js";

const browser = await chromium.launch();
const page = await browser.newPage({ deviceScaleFactor: 1 });

async function png(size, square) {
  const src = "data:image/svg+xml," + encodeURIComponent(faviconSvg(DEFAULT_PALETTE, square));
  await page.setContent(`<body style="margin:0"><img id="i" width="${size}" height="${size}" src="${src}">`);
  return page.locator("#i").screenshot({ omitBackground: true });
}

/** An ICO file that holds PNGs, which every browser since IE 9 reads. */
function ico(images) {
  const header = Buffer.alloc(6 + 16 * images.length);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach(({ size, data }, n) => {
    const at = 6 + 16 * n;
    header.writeUInt8(size % 256, at);
    header.writeUInt8(size % 256, at + 1);
    header.writeUInt16LE(1, at + 4);
    header.writeUInt16LE(32, at + 6);
    header.writeUInt32LE(data.length, at + 8);
    header.writeUInt32LE(offset, at + 12);
    offset += data.length;
  });
  return Buffer.concat([header, ...images.map((x) => x.data)]);
}

const apple = await png(180, true);
// One at a time: the renders share a page.
const sizes = [];
for (const size of [16, 32, 48]) sizes.push({ size, data: await png(size, false) });
const favicon = ico(sizes);
await browser.close();

fs.writeFileSync(
  new URL("../src/output/icons.ts", import.meta.url),
  `// Generated by scripts/make-icons.mjs from the favicon SVG in theme.ts. Do not edit by hand.

/** Files written to the site root alongside index.html. */
export const ROOT_ICONS: Record<string, string> = {
  "apple-touch-icon.png": "${apple.toString("base64")}",
  "favicon.ico": "${favicon.toString("base64")}",
};
`,
);
console.log(`apple-touch-icon.png ${apple.length} bytes, favicon.ico ${favicon.length} bytes → src/output/icons.ts`);
